### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by RobertDiebels** [Mordred/aurelia-sails-socket-client#1]
Hi @Mordred ,

I've just finished setting up a sails app which serves an aurelia app and I'm quite interested in this plugin. Is there anything special I need to do to get this running?

**Comment by Mordred** [comment]
Hi @RobertDiebels,

I have added example directory to the repository. Please check it. It is http://todomvc.com/ application implemented with Aurelia and Sails.

**Comment by RobertDiebels** [comment]
Very cool thank you!
