### ISSUE TITLE
Running example app

### ISSUE THREAD

**Issue by kristianmandrup** [Mordred/aurelia-sails-socket-client#3]
Ran through all the install/setup instructions on the main README, then tried out your example app:

```
npm install
sails lift
```

However I get a `System is not defined` error in browser control, after opening `localhost:1337`
Then I tried  `jspm install -y` since I could see some jspm entries in the `example/packages.json` file

```
  "jspm": {
    "directories": {
      "baseURL": "assets"
    },
    "dependencies": {
      "aurelia-animator-css": "github:aurelia/animator-css@^0.2.0",
```

However... 

```
warn Error on getPackageConfig for github:aurelia/router, retrying (1).

     GitHub rate limit reached. To increase the limit use GitHub authentication.
     Run jspm registry config github to set this up, or add the credentials to your ~/.netrc file.
```

But I guess this is an issue with my own settings I need to fix. Would be nice with some instructions for running example app in the main README. Cheers :)

Tip: Run `jspm registry config github` in order to fix this locally if this problem is encountered :)

**Comment by kristianmandrup** [comment]
Awesome! Got it running :)

**Comment by Mordred** [comment]
You didn't run `jspm install` after `npm install`.

I have added _How to run_ to README for example app. https://github.com/Mordred/aurelia-sails-socket-client/blob/master/example/README.md

**Comment by kristianmandrup** [comment]
Thanks :)
