### ISSUE TITLE
Socket

### ISSUE THREAD

**Issue by johntom** [Mordred/aurelia-sails-socket-client#4]
Hi,
I just installed your repo and followed instructions for the example directory. I then opened 2 browers expecting to see each browser updated on socket when adding todo but nothing was updated.
Thanks for this repo as I think this combo will be awesome.
john
Windows 10
Node 0.12.7
npm 2.13.4

**Comment by Mordred** [comment]
Hi .. currently there is no support for subscribing to sails blueprints events (PubSub). I will add this feature, but I'm little bit busy now. You can make PR if you want.

**Comment by Mordred** [comment]
I've added `client.on(event, fn)` and `client.off(event, fn)`. Please check the example and `0.6.0` release for more details.

**Comment by johntom** [comment]
Thanks sockets now work
