### ISSUE TITLE
Post message isn't picking up url but picking base url

### ISSUE THREAD

**Issue by rahulravindran0108** [Mordred/aurelia-sails-socket-client#5]
This is my code for the backend:

```
this.sails.post("/login", credentials)
      .then((response) => alert("Success login"))
      .catch((response) => alert("Wrong credentialsssss!!"));
```

Getting the following error on js console. Even if I am sending a post the socket message reads as get and the ur; is not being picked up.

```
SocketRequestMessage {method: "get", url: "/csrfToken", content: undefined, headers: Headers, baseUrl: "http://localhost:1337"…}
baseUrl: "http://localhost:1337"
content: undefined
headers: Headers
interceptors: Array[2]
method: "get"
options: (...)
url: "/csrfToken"
__proto__: SocketRequestMessage
constructor: SocketRequestMessage(method, url, content, headers)
options: (...)
get options: ()
__proto__: Object
```

**Comment by Mordred** [comment]
Can you post plugins setup? I think you have added a `CSRFInterceptor` and didn't enable CSRF protection in the [Sails config](http://sailsjs.org/documentation/concepts/security/csrf).

`CSRFInterceptor` will fetch CSRF token before sending non-GET request.

If you don't want to have CSRF protection, remove this interceptor from setup.

**Comment by rahulravindran0108** [comment]
The following is my code for configuration

```
  aurelia.use.plugin('aurelia-sails-socket-client', (sails, io) => {
    sails.configure(x => {
      //console.log(x);
      //console.log(io);
      let config = new Config();
      if(config.debugMode)
        io.sails.url = config.debugSailsUrl;
      x.withBaseUrl(config.debugSailsUrl);
      // Example for CSRFInterceptor
      x.withInterceptor(new CSRFInterceptor('/csrfToken', sails));
      x.withInterceptor(new LoggerInterceptor());
    });

  });
```

Also, in your readme, you have mentioned `x.withBaseUri` which is no longer present. My code seems to configuring the client properly and also connects well. I have been using socket.request to make get/put/post requests for now.

**Comment by Mordred** [comment]
Thanks - I have fixed README typo `x.withBaseUri`.

> Another issue was this.sails.get(.....) was doing a post request for some reason.I kind of felt this behaviour odd!

Can you be more specific?

**Comment by rahulravindran0108** [comment]
Sorry for the last part of the comment. Edited it out!

**Comment by Mordred** [comment]
OK, so is this issue fixed?

**Comment by rahulravindran0108** [comment]
Yes, its working now. Closing it. Thank you very much for solving.
