### ISSUE TITLE
Cannot lift example in production mode

### ISSUE THREAD

**Issue by JasonWeise** [Mordred/aurelia-sails-socket-client#6]
Hey 
Thanks for the excellent example. I am coming from Meteor and love both Aurelia and Sails and your example works great with `sails lift`.

but...

If I execute with `sails lift --prod` to execute in production mode the example doesn't work.
The error in Chrome console is:

```
http://localhost:1337/js/production.js Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:1337/js/production.js
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:1337/js/production.js(…)
```

The error from sails is:

```
sails-hook-sockets :: connected to Sails admin message bus.
Rendering view: "homepage" (located @ "C:\Users\Jason\Documents\Visual Studio 2015\Projects\Aurelia-Sails-Sockets\views\homepage")
• using configured layout:: layout (located @ "C:\Users\Jason\Documents\Visual Studio 2015\Projects\Aurelia-Sails-Sockets\views\layout")
Sending 404 ("Not Found") response
Rendering view: "homepage" (located @ "C:\Users\Jason\Documents\Visual Studio 2015\Projects\Aurelia-Sails-Sockets\views\homepage")
• using configured layout:: layout (located @ "C:\Users\Jason\Documents\Visual Studio 2015\Projects\Aurelia-Sails-Sockets\views\layout")
Sending 404 ("Not Found") response
```

These errors do not occur with `sails lift` and this is the example exactly as it was downloaded today.

Thanks for any advice you can provide.

**Comment by Mordred** [comment]
Hi, I have fixed example and also update bootstraping, because manual bootstraping has some bugs (https://github.com/aurelia/templating-resources/issues/173)

But I recommend you to setup https://github.com/aurelia/bundler to bundle your `production.js` file instead of the sails's default `prod` grunt task.

**Comment by JasonWeiseUnreal** [comment]
Thanks so much, that got it working though I think I might have other issues that are probably not related to your example and more JSPM (maybe).

Your recent commit works in Chrome but Internet Explorer 11 is failing with 'system' is undefined and refers to production.min.js.

As a side note, I think I might need to look at the Aurelia bundler as the number of requests just opening the example in Chrome sits at 362 (in production mode).

As I am just getting my head around Aurelia, don't suppose you have any advice on how to configure the Aurelia bundler when integrated like this. The Aurelia docs work great for a Vanilla demo of Aurelia, but in an example like yours I cannot see where I need to make the changes (or how I move it from grunt to the Aurelia bundler)

Sorry if too many questions and I understand if they are outside the scope of supporting this example, I really like this solution to real-time web you have here and just trying to get my head around how it all integrates.

Cheers :)

**Comment by Mordred** [comment]
You are lucky man :) I had some time today so I have fixed toggling todo after some Aurelia changes. Also, I have updated Aurelia packages for example and have added simple `bundle` task to grunt.
