### ISSUE TITLE
Separate backend/frontend

### ISSUE THREAD

**Issue by johntom** [Mordred/aurelia-sails-socket-client#7]
Hi,
Thanks for this repo. I'm a long time user of sails and past contributor (https://github.com/SharePointOscar/MEANS, nodemachines etc). Have been using Aurelia since June and I'm hooked. Currently I'm using sails as a separate backend rest service with Aurelia on the frontend using fetch. I'd like to explore this socket example separating each part and before I start I was wondering what thoughts you might have and I'f you'd like to collaborate. I'd like to wind up with a means stack, just a different A and as a backend and frontend service similar to tarlap's example with Angular (https://github.com/tarlepp/angular-sailsjs-boilerplate).
John

**Comment by Mordred** [comment]
Yeah, sure
