### ISSUE TITLE
Connections outside an isomorphic sails app doesn't seem to work.

### ISSUE THREAD

**Issue by JasonWeise** [Mordred/aurelia-sails-socket-client#8]
I hope the title is the correct terminology..

Basically I am trying to have an Aurelia App(running on localhost:9000) connect to a sails app running (localhost:1337) and cannot get the aurelia-sails-socket-client to connect.

I have mostly replicated the example you have provided by tried to break the example into two separate components.

The error I am getting in the Chrome console is:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1455165127101-1
sails.io.js:156  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #2)
```

I have changed the items where I think I need to and have tried modifying `main.js` in the Aurelia app to be the following:

```
.plugin('aurelia-sails-socket-client', (sails) => {
      sails.configure(x => {
x.withBaseUrl('http://localhost:1337/api/v1');
*** and have tried leaving it as x.withBaseUrl('/api/v1');
```

and changed the lines in `app.js` (Aurelia App) to be like: (I have changed all the relevant lines to be like this...

```
addTodo(todo) {
      this.sails.post('http://localhost:1337/todos', todo).then((response) => {
      this.todos.push(new Todo(response.body));
      this.todo = new Todo({
        title: '',
        completed: false
      });
    });
  }
```

I'm sure I should be able to connect the two apps together but for the life I me cannot get this to work. The console on sails app with silly logging doesn't even register that the Aurelia app has tried to make a connection.

Any advice? Thanks heaps in advance. (I hope I'm not doing something stupid)

**Comment by Mordred** [comment]
Oh .. I see .. OK, `withBaseUrl` is not so good naming. We should rename it. It should be more like `withPrefix` or similar, but it is a breaking change. Maybe after Aurelia v1.0.0 release?

If you want to connect to another host, you must configure `sails.io.js` library directly. It is passed as second argument for config function of plugin.

``` js
aurelia.use
    .plugin('aurelia-sails-socket-client', (sails, io) => {
      sails.configure(x => {
        io.sails.url = 'http://localhost:9000';
        x.withBaseUrl('/api/v1');
      });
    });
```

**Comment by JasonWeise** [comment]
Thanks so much for helping with this, really appreciated.
I had dived into your src and did notice I could append the url to io.sails.url like you have demonstrated

After doing that I didn't think it was right as now after doing that I am getting a connection to the sails server ok but am receiving a CSRF error when trying to post a new todo.

The error in chrome console is now:

```
Unhandled promise rejection SocketResponseMessage {requestMessage: SocketRequestMessage, statusCode: 403, body: "CSRF mismatch", isSuccess: false, headers: Headers}
```

This is from the Aurelia App

**Comment by Mordred** [comment]
Yeah, this is little bit complicated. You have to setup your sails app. In your `config/csrf.js` make some changes:

``` js
module.exports.csrf = {
  grantTokenViaAjax: true,
  protectionEnabled: true,
  origin: 'http://localhost:1337',
  routesDisabled: '-'
};
```

Also CORS should be modified.

**Comment by johntom** [comment]
Hi Jason,
See https://github.com/Mordred/aurelia-sails-socket-client/issues/7. Any chance you'd like to share and be a contributor.
John

**Comment by JasonWeise** [comment]
@Mordred thanks so much for all your assistance. This is working perfectly now as two separate front/end back end solutions. I appreciate all your help.
If you lived in Australia I'd deliberately go out of my way to come and buy you a beer next time I was in your neck of the woods (I travel a bit LOL)

@johntom once I have tidied up my code I'd be happy to help with what I have. As a regular contributor I'm not sure how much value I would be just now. I am just coming into the node world as I have always developed in C#, ASP.NET for our corporate web apps and have in the last 12 months produced two production apps with Meteor (that was a nice experience). I am loving the node ecosystem and LOVE Aurelia and Sails - this is the perfect fit for my next projects and @Mordred's work with this has sealed the deal with me. A lot of the Node/Express/...{WHATEVER MIDDLEWARE} stuff still has me scratching my head.. but I am loving it. - Thanks so much for the offer :+1:
