### ISSUE TITLE
disabled autoconnect

### ISSUE THREAD

**Issue by AngelMunoz** [Mordred/aurelia-sails-socket-client#9]
Hi, I'm using this project with my aurelia-sails applications it's working great but I have a question, is there any partocular reason  autoconnect is disabled?
I see it was disabled in [this commit](https://github.com/Mordred/aurelia-sails-socket-client/commit/2f7d43c5cbad62fb6bfa6b05e84e188267a5e49f) and I added it on my plugin configuration but no luck so far on reconnecting
this is my conf 
```js
.plugin('aurelia-sails-socket-client', (sails, io) => {
      sails.configure(conf => {
        if (environment.debug) {
          io.sails.url = devConf.sailsSocketURL;
          io.sails.autoConnect = true;
          conf.withBaseUrl(devConf.sailsSocketURL);
          conf.withInterceptor(new LoggerInterceptor());
        } else {
          conf.withBaseUrl(prodConf.sailsSocketURL);
          io.sails.url = prodConf.sailsSocketURL;
        }
      });
    })
```

**Comment by Mordred** [comment]
Hi,

autoconnect is disabled, because we are manually connecting socket: https://github.com/Mordred/aurelia-sails-socket-client/blob/master/src/index.js#L15

You don't have to set it to `true` again.
